### ISSUE TITLE
Week 2 Coding Challenge deadline 

### ISSUE THREAD

**Issue by lucap1211** [earthlab-education/Earth-Analytics-2023-01-Intro#206]
Hi All,

I got confused about our upcoming deadline for Week 2. When I go to the repository that was created for the coding challenge, I find Sept 11, the main Github page's Wiki - Upcoming Due dates show Sept 12, and I also got an email from Canvas about Sept 15. Can someone clarify which date should be the correct one?

Thanks!

**Comment by eculler** [comment]
Hi @lucap1211, the coding assignment is due on the 12. The deadline in Canvas is for posting the link to your independent analysis (same analysis in a location of your choosing). We haven't showed you all how to submit those yet, so the due date is after the discussion sections this week. In the future, they will be due on the same day.

**Comment by lucap1211** [comment]
Thanks for the quick clarification!
