### ISSUE TITLE
[DISCUSSION GUIDE] Week 7: Who draws maps?

### ISSUE THREAD

**Issue by eculler** [earthlab-education/Earth-Analytics-2023-01-Intro#491]
# Agenda
1. Warm-up: what's your favorite map? [5 min]
2. [Read and Discuss](https://github.com/earthlab-education/Earth-Analytics-2023-01-Intro/discussions/490) [30 min]
3. Everyone make or respond to a discussion post about a problem they had with the vector homework. [5-10 min] It could be a problem they were able to solve - this is an opportunity to practice making useful discussion posts. Discussion posts should contain at a minimum:
  * **What were you trying to do?** What output or behavior did you expect?
  * **What *did* you do?** (include a minimal reproducible code example)
  * **What actually happened?** (include FULL error messages and screenshots as needed)
  * Describe your system. This is pretty easy if you use a Codespace. Otherwise it is REALLY important. Consider including operating system/container system, how you installed your environment, output of `conda list`.
4. Choose one or two to answer as a class. Please also critique the discussion posts - do they have enough information to answer the question? I don't expect students to be able to solve every coding problem they encounter at this point (or maybe ever!). I do expect them to be able to describe the problem they have in a clear and helpful way. If as a class there is a well-described problem and you can't find the answer, tag @eculler !
5. Screen share - Continue from the data download.

**Comment by nquarder** [comment]
From Nate's Weds afternoon discussion - 
* What are some of peoples favorite maps?
* @peterkobylarz likes to your Gaia GPS (https://www.gaiagps.com); use for backcountry navigation; cool tool that allows overlay of different base maps; mushroom foraging (private property layers; aerial photos; has a free version; also likes https://store.avenza.com as well as ArcGIS Pro; NOAA digital coast searchable for datasets and LiDAR, coasts, waterways (https://coast.noaa.gov/dataviewer/#/lidar/search/); fire data and maps (https://www.watchduty.org/) - useful for monitoring staying notified
* @jsmi374 likes https://tnris.org/ ; Texas Natural Resources Information System; in a previous job did desktop analysis using LiDAR; TX has good database of spatial data for free online; better than a lot of other states' open GIS tools; paleo river maps of the Mississippi River (https://kottke.org/19/06/the-marvelous-mississippi-river-meander-maps)
* @annettebalmes likes Science on a Sphere (NOAA tool) - way to see things in 3D; https://sos.noaa.gov/catalog/datasets/?category=Space&subcategory=Earth%27s%20Magnetism&platform=sos
* @Adriannaluger has used the ESRI tools 
* @nquarder has used https://ortho.gis.iastate.edu/ for work specific to Iowa 

Link to survey for anyone who still needs to take: https://cuboulder.qualtrics.com/jfe/form/SV_5uu3DOLPZkgIPUq

Demonstrate how to ask/answer Q's in GitHub

**Comment by eculler** [comment]
\adminteamassign @earthlab-education/ea-instructors
