### ISSUE TITLE
[DISCUSS] Broken link to image in portfolio?

### ISSUE THREAD

**Issue by peterkobylarz** [earthlab-education/Earth-Analytics-2023-01-Intro#77]
@nquarder 
I added an image to my portfolio page. I added the image file to my repository then added it via markdown. It displays in the preview but on the actual site, it appears as a broken link. Any ideas what is going on? Here's the site URL:

https://peterkobylarz.github.io/

Here is the path to the image:

https://github.com/peterkobylarz/peterkobylarz.github.io/blob/main/images/PDC.png

**Comment by peterkobylarz** [comment]
I just reloaded the page and the image appears to be loading now... Not sure why it was appearing as broken but I guess this issue is resolved!

**Comment by nquarder** [comment]
Hey @peterkobylarz ! Yes sometimes it can take a few minutes for changes to show up on your published GH page. Yours looks great!! What theme did you use? Also can you figure out how to make the text to your github, email, linkedin hot links?

Again, this is a great looking page. Very well done!

**Comment by peterkobylarz** [comment]
I used the "Tactile" theme. I was able to make my URLs live using markup. Thanks!
